#配置数据库
#mysql
spring:
  datasource:
    #mysql配置
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动
    url: jdbc:mysql://localhost:3306/bs202206?useUnicode=true&characterEncoding=UTF-8&useSSL=false #连接数据库
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model

server:
  port: 9000
#  servlet:
#    context-path: /api